[build]
    functions = "functions"
    external_node_modules = ["express", "cors", "cloudinary", "dotenv", "multer", "sharp"]
    node_bundler = "esbuild"

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"