[functions]
  included_files = ["node_modules/@sharpen/**"]


[build]
    functions = "functions"
    node_bundler = "esbuild"

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"